### ISSUE TITLE
Memory Consumption

### ISSUE THREAD

**Issue by jeff8688** [ConSol-Monitoring/snclient#117] opened 2024-05-02 11:37 UTC
Hi,

I am seeing an constant increase in memory consumption on our Windows servers when I use snclient+ instead of nsclient++. I am surprised that no one else seems to have encountered this problem. Could it be related to a configuration in the ini?

I am testing the latest version.

Thank you in advance.

Best regards,

Jeff

**Comment by sni** [comment] 2024-05-02 11:39
which windows version is that?

**Comment by jeff8688** [comment] 2024-05-02 11:41
Windows Server 2022 standard

**Comment by jeff8688** [comment] 2024-05-02 11:44
![memory](https://github.com/ConSol-Monitoring/snclient/assets/111570485/ca86d114-e26d-49ef-a884-bdb5843a8120)

**Comment by pyves007** [comment] 2024-05-02 11:49
After restarting the snclient service :
![image](https://github.com/ConSol-Monitoring/snclient/assets/58570757/c8817250-5f64-4e4a-aa9f-8bfcaaa0dd1f)
The memory was increasing also with previous versions, the version in place was 0.22, let's see with the version 0.23.

**Comment by sni** [comment] 2024-05-02 12:07
i can see this with windows 11 as well, i bet it is connected to some wmi queries...

**Comment by jeff8688** [comment] 2024-05-02 12:19
we 
![checks](https://github.com/ConSol-Monitoring/snclient/assets/111570485/0b1e9a95-e352-421e-8859-d53bec9f50e0)
use the following checks. Nothing special.

**Comment by FranckSallet** [comment] 2024-05-03 06:25
Hi

I have the same behavior on Windows 2016

![snclient_after](https://github.com/ConSol-Monitoring/snclient/assets/132520562/2be10fe0-5103-435d-a61d-faaa5ffa1b43)
![snclient_before](https://github.com/ConSol-Monitoring/snclient/assets/132520562/2f6a9e8e-ed8e-4766-bcf9-2ddad70c240e)

**Comment by Gent00157** [comment] 2024-05-03 07:33
BTW: I do not see any problem with snclient version 0.20.0 (64bit) with NRPE checks - I have 100+ Windows servers (2012-2022) and snclient using ~100MB memory, uptime more than 1 month (using only standard checks, not any wmi).

**Comment by pyves007** [comment] 2024-05-03 07:58
Hello, could you list the checks used by snclient ? May i ask you also your snclient.ini (anonymized) then we can compare what options are activated or not. Thanks in advance, Pyves

**Comment by sni** [comment] 2024-05-03 08:07
that would be helpful, but some windows checks also use wmi internally. Altough i think the leak is in the generic check_wmi, not in the others which use wmi internally. They use
different libraries internally because the check_wmi cannot use fixed known objects.

**Comment by Gent00157** [comment] 2024-05-03 11:12
Hi,
sure, you can find my .ini bellow used on most of the servers. I am using external command (and powershell wrapper) for networking, because I get some strange behavior with NSclient++ in past - it is not related to snclient. Also notice, that I wrap powershell scripts old way and AFAIK there is a better/cleaner way how to call it with snclient using `[/settings/external scripts/wrappings]`. As noted above, I am using "old" 0.20.0 (64bit) version, so it seems to be memory leak somewhere in newer version. (and btw I use ssh and nrpe on linux, not snclient).

```
[/paths]
exe-path =
shared-path =
scripts = ${shared-path}/scripts
certificate-path = ${shared-path}/ssl


[/modules]
NRPEServer = enabled
CheckSystem = enabled
CheckDisk = enabled
CheckExternalScripts = enabled
WEBServer = disabled
WEBAdminServer = disabled
PrometheusServer = disabled
NodeExporterServer = disabled
WindowsExporterServer = disabled
ExporterExporterServer = disabled
ManagedExporterServer = disabled
CheckBuiltinPlugins = disabled
CheckSystemUnix = disabled
CheckWMI = disabled


[/settings/default]
allowed hosts = 192.168.1.1
cache allowed hosts = true
timeout = 30
bind to =
tls min version = tls1.3
nasty characters = $|`&><'\"\"'\\[]{}
use ssl = true
certificate = ${certificate-path}/server.crt
certificate key = ${certificate-path}/server.key
client certificates = ${certificate-path}/ca.pem
password =


[/settings/NRPE/server]
insecure = false
allow nasty characters = false
port = 5666
allow arguments = false
use ssl = enabled


[/settings/external scripts]
timeout = 60
allow nasty characters = false
allow arguments = false
script root = ${scripts}
script path =
ignore perfdata = no


[/settings/external scripts/wrappings]
ps1 = powershell.exe -ExecutionPolicy Bypass -File %SCRIPT% %ARGS%


[/settings/external scripts/alias]
alias_cpu = check_cpu "warn=load > 90" "crit=load > 95"
alias_mem = check_memory "warn=used > 90%" "crit=used > 95%" "type=physical" "perf-config=*(unit:B)"
alias_uptime = check_uptime "warn=uptime<2m" "crit=uptime<1m"
alias_disk = check_drivesize "warn=free<10%" "crit=free<5%" "perf-config=*(unit:B)" drive=c:
alias_shared_disk = check_drivesize "warn=free<10%" "crit=free<5%" "perf-config=*(unit:B)" drive=f: drive=g: drive=h: drive=i:
alias_services = check_service "service=LanmanServer" "service=ClusSvc"

[/settings/external scripts/scripts]
alias_net = cmd /c echo scripts\net.ps1 "NIC1,NIC2,NIC3,NIC4,TEAM1"; exit($lastexitcode) | powershell.exe -command -
alias_wupdate = cmd /c echo scripts\wupdate.ps1; exit($lastexitcode) | powershell.exe -command -

[/settings/log]
file name = ${shared-path}/snclient.log
level = info


[/settings/log/file]
max size = 20MiB


[/settings/updates]
automatic updates = disabled
automatic restart = disabled
```

**Comment by sni** [comment] 2024-05-06 20:57
found something in the windows check_service and check_drivesize, could you try the latest builds to see if it helped?

**Comment by sni** [comment] 2024-05-07 06:48
![image](https://github.com/ConSol-Monitoring/snclient/assets/150844/86cd7797-f159-44e8-aa41-ed206a0f60d0)

I'd say it looks a bit better, but it's too early to finally say it's gone. I'll keep it open until we know...

**Comment by FranckSallet** [comment] 2024-05-07 08:51
the problem seems not to be resolved in the release 0.23
![snclient_before](https://github.com/ConSol-Monitoring/snclient/assets/132520562/01951787-1da6-494f-b337-ddf22814fc0d)

![snclient_after](https://github.com/ConSol-Monitoring/snclient/assets/132520562/aea79b8e-e952-4e45-93fe-eb664286901a)

**Comment by sni** [comment] 2024-05-07 08:56
right, i haven't made a release yet, i was talking about the v0.23.0034 nightly build. In my tests it still seems to grow, but not as bad as before.

**Comment by sni** [comment] 2024-05-08 12:42
i can still reproduce a leak when using check_drivesize. I'll let you know when it's fixed.

**Comment by sni** [comment] 2024-05-09 18:08
![image](https://github.com/ConSol-Monitoring/snclient/assets/150844/06121c98-a5e6-40ac-8687-f2e47d33c175)

Could you try the latest nightly ( >= 0.23.0041 ) now, it looks promising...

**Closed** 2024-05-20 16:22 UTC

**Comment by jeff8688** [comment] 2024-05-21 08:14
Hi,

thank you for your help. Will you create a new release?

Best regards,

Jeff

________________________________
Von: Sven Nierlein ***@***.***>
Gesendet: Montag, 20. Mai 2024 18:22
An: ConSol-Monitoring/snclient ***@***.***>
Cc: jeff8688 ***@***.***>; Author ***@***.***>
Betreff: Re: [ConSol-Monitoring/snclient] Memory Consumption (Issue #117)


Closed #117<https://github.com/ConSol-Monitoring/snclient/issues/117> as completed.

**Comment by sni** [comment] 2024-05-21 08:15
already done, that's the 0.24.

**Comment by jeff8688** [comment] 2024-05-21 08:27
Thanks, it was confusing because you see still version 0.23 on the main page. I have found 0.24 now.
________________________________
Von: Sven Nierlein ***@***.***>
Gesendet: Dienstag, 21. Mai 2024 10:16
An: ConSol-Monitoring/snclient ***@***.***>
Cc: jeff8688 ***@***.***>; Author ***@***.***>
Betreff: Re: [ConSol-Monitoring/snclient] Memory Consumption (Issue #117)


already done, that's the 0.24.

**Comment by sni** [comment] 2024-05-21 08:29
did i forget to update something? Which main page do you mean?

**Comment by jeff8688** [comment] 2024-05-21 08:38
on this page, you still see version 23 as latest one: https://github.com/ConSol-Monitoring/snclient


________________________________
Von: Sven Nierlein ***@***.***>
Gesendet: Dienstag, 21. Mai 2024 10:29
An: ConSol-Monitoring/snclient ***@***.***>
Cc: jeff8688 ***@***.***>; Author ***@***.***>
Betreff: Re: [ConSol-Monitoring/snclient] Memory Consumption (Issue #117)


did i forget to update something? Which main page do you mean?

**Comment by jeff8688** [comment] 2024-05-21 08:38
[cid:b5d69a8c-acf7-413b-a284-111461861c1f]
________________________________
Von: Jeff Weitzmann ***@***.***>
Gesendet: Dienstag, 21. Mai 2024 10:37
An: ConSol-Monitoring/snclient ***@***.***>; ConSol-Monitoring/snclient ***@***.***>
Cc: Author ***@***.***>
Betreff: AW: [ConSol-Monitoring/snclient] Memory Consumption (Issue #117)

on this page, you still see version 23 as latest one: https://github.com/ConSol-Monitoring/snclient


________________________________
Von: Sven Nierlein ***@***.***>
Gesendet: Dienstag, 21. Mai 2024 10:29
An: ConSol-Monitoring/snclient ***@***.***>
Cc: jeff8688 ***@***.***>; Author ***@***.***>
Betreff: Re: [ConSol-Monitoring/snclient] Memory Consumption (Issue #117)


did i forget to update something? Which main page do you mean?

**Comment by FranckSallet** [comment] 2024-05-23 07:57
> already done, that's the 0.24.

where we can find the 0.24 release ?

**Comment by sni** [comment] 2024-05-23 10:52
I forgot to press the release button :-) It is here now
